/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.AjusteCurvas;
import java.awt.Component;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import rojerusan.RSButtonIconI;

/**
 *
 * @author cesit
 */
public class PAjusteC extends javax.swing.JPanel {

    JPanel pnlCentral;
    private int x, y;
    RSButtonIconI btnAux;
    int fila = -1;
    Object[] vector = new Object[2];
    AjusteCurvas objAjuste;
    double[] valores;
    String tipoFuncion;

    /**
     * Creates new form PRaices
     */
    public PAjusteC() {
        initComponents();
        this.personalizacion();
        this.pnlMejorAjuste.setVisible(true);
    }

    private void personalizacion() {
        this.x = this.pnlCentro.getX();
        this.y = this.pnlCentro.getY();

        pnlCentral = this.pnlCentro;
        Teclado teclado = new Teclado();
        teclado.setVisor(visor1);
        this.viewPanelCentro(teclado, null);
        this.repaint();

    }

    public void viewPanelCentro(Object jp, java.awt.event.MouseEvent evt) {
        try {
            //this.remove(this.getContentPane().getComponentAt(x, y));
            //this.remove(this.getComponentAt(x, y));
            //this.repaint();
            //this.getContentPane().add((Component) jp, BorderLayout.CENTER);
            //this.add((Component) jp);
            this.pnlCentro.add((Component) jp);

            this.getComponentAt(x, y).setPreferredSize(new Dimension(100, 100));
            this.revalidate();

            if (evt != null) {
                btnAux.setSelected(false);
                btnAux = (RSButtonIconI) evt.getSource();
                btnAux.setSelected(true);
            }

            this.repaint();

        } catch (Exception e) {
            System.out.println(e.getMessage() + "exception");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlOpcMetodo1 = new javax.swing.JPanel();
        rSButtonIconI5 = new rojerusan.RSButtonIconI();
        rSButtonIconI7 = new rojerusan.RSButtonIconI();
        rSButtonIconI8 = new rojerusan.RSButtonIconI();
        rSButtonIconI9 = new rojerusan.RSButtonIconI();
        rSButtonIconI10 = new rojerusan.RSButtonIconI();
        frame2 = new javax.swing.JFrame();
        pnlMejorAjuste = new javax.swing.JPanel();
        lblTipoFuncion = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaValores = new rojerusan.RSTableMetro();
        jLabel1 = new javax.swing.JLabel();
        lblDesvi = new javax.swing.JLabel();
        rSButtonRound1 = new rojerusan.RSButtonRound();
        pnlVista = new javax.swing.JPanel();
        visor1 = new Visor.Visor();
        pnlDatos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new rojerusan.RSTableMetro();
        btnAdd = new rojerusan.RSButtonMetro();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtValy = new javax.swing.JTextField();
        txtValx = new javax.swing.JTextField();
        btnDelete = new rojerusan.RSButtonMetro();
        pnlCentro = new javax.swing.JPanel();
        btnCalcularAjuste = new rojerusan.RSMaterialButtonCircle();

        pnlOpcMetodo1.setLayout(new javax.swing.BoxLayout(pnlOpcMetodo1, javax.swing.BoxLayout.LINE_AXIS));

        rSButtonIconI5.setBackground(new java.awt.Color(204, 204, 204));
        rSButtonIconI5.setForeground(new java.awt.Color(0, 0, 0));
        rSButtonIconI5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/transparente.png"))); // NOI18N
        rSButtonIconI5.setText("LINEAL");
        rSButtonIconI5.setColorHover(new java.awt.Color(153, 153, 153));
        rSButtonIconI5.setColorText(new java.awt.Color(0, 0, 0));
        rSButtonIconI5.setColorTextHover(new java.awt.Color(0, 0, 0));
        pnlOpcMetodo1.add(rSButtonIconI5);

        rSButtonIconI7.setBackground(new java.awt.Color(204, 204, 204));
        rSButtonIconI7.setForeground(new java.awt.Color(0, 0, 0));
        rSButtonIconI7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/transparente.png"))); // NOI18N
        rSButtonIconI7.setText("EXPONENCIAL");
        rSButtonIconI7.setColorHover(new java.awt.Color(153, 153, 153));
        rSButtonIconI7.setColorText(new java.awt.Color(0, 0, 0));
        rSButtonIconI7.setColorTextHover(new java.awt.Color(0, 0, 0));
        pnlOpcMetodo1.add(rSButtonIconI7);

        rSButtonIconI8.setBackground(new java.awt.Color(204, 204, 204));
        rSButtonIconI8.setForeground(new java.awt.Color(0, 0, 0));
        rSButtonIconI8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/transparente.png"))); // NOI18N
        rSButtonIconI8.setText("LOGARITMICA");
        rSButtonIconI8.setColorHover(new java.awt.Color(153, 153, 153));
        rSButtonIconI8.setColorText(new java.awt.Color(0, 0, 0));
        rSButtonIconI8.setColorTextHover(new java.awt.Color(0, 0, 0));
        pnlOpcMetodo1.add(rSButtonIconI8);

        rSButtonIconI9.setBackground(new java.awt.Color(204, 204, 204));
        rSButtonIconI9.setForeground(new java.awt.Color(0, 0, 0));
        rSButtonIconI9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/transparente.png"))); // NOI18N
        rSButtonIconI9.setText("POTENCIAL");
        rSButtonIconI9.setColorHover(new java.awt.Color(153, 153, 153));
        rSButtonIconI9.setColorText(new java.awt.Color(0, 0, 0));
        rSButtonIconI9.setColorTextHover(new java.awt.Color(0, 0, 0));
        pnlOpcMetodo1.add(rSButtonIconI9);

        rSButtonIconI10.setBackground(new java.awt.Color(204, 204, 204));
        rSButtonIconI10.setForeground(new java.awt.Color(0, 0, 0));
        rSButtonIconI10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/transparente.png"))); // NOI18N
        rSButtonIconI10.setText("MULTIPLE");
        rSButtonIconI10.setColorHover(new java.awt.Color(153, 153, 153));
        rSButtonIconI10.setColorText(new java.awt.Color(0, 0, 0));
        rSButtonIconI10.setColorTextHover(new java.awt.Color(0, 0, 0));
        pnlOpcMetodo1.add(rSButtonIconI10);

        lblTipoFuncion.setText("Forma");

        tablaValores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "VALORES"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaValores.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tablaValores.setGridColor(new java.awt.Color(255, 255, 255));
        tablaValores.setRowHeight(30);
        jScrollPane2.setViewportView(tablaValores);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("DESVIACIÓN ESTANDAR");

        lblDesvi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDesvi.setText("0");

        rSButtonRound1.setText("Cerrar");
        rSButtonRound1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMejorAjusteLayout = new javax.swing.GroupLayout(pnlMejorAjuste);
        pnlMejorAjuste.setLayout(pnlMejorAjusteLayout);
        pnlMejorAjusteLayout.setHorizontalGroup(
            pnlMejorAjusteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMejorAjusteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMejorAjusteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTipoFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(lblDesvi, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMejorAjusteLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(rSButtonRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlMejorAjusteLayout.setVerticalGroup(
            pnlMejorAjusteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMejorAjusteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTipoFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDesvi, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rSButtonRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout frame2Layout = new javax.swing.GroupLayout(frame2.getContentPane());
        frame2.getContentPane().setLayout(frame2Layout);
        frame2Layout.setHorizontalGroup(
            frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 254, Short.MAX_VALUE)
            .addGroup(frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(frame2Layout.createSequentialGroup()
                    .addGap(0, 27, Short.MAX_VALUE)
                    .addComponent(pnlMejorAjuste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 27, Short.MAX_VALUE)))
        );
        frame2Layout.setVerticalGroup(
            frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
            .addGroup(frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(frame2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlMejorAjuste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        visor1.setEditable(false);
        visor1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N

        pnlDatos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data A", "Data B"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        btnAdd.setText("AGREGAR");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jPanel5.setOpaque(false);

        jLabel2.setText("DATO A");

        jLabel3.setText("DATO B");

        txtValy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValyKeyTyped(evt);
            }
        });

        txtValx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValxActionPerformed(evt);
            }
        });
        txtValx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValxKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtValx, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtValy)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtValx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtValy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btnDelete.setText("BORRAR");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlCentro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        pnlCentro.setLayout(new java.awt.BorderLayout());

        btnCalcularAjuste.setText("CALCULAR");
        btnCalcularAjuste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularAjusteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlVistaLayout = new javax.swing.GroupLayout(pnlVista);
        pnlVista.setLayout(pnlVistaLayout);
        pnlVistaLayout.setHorizontalGroup(
            pnlVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVistaLayout.createSequentialGroup()
                .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVistaLayout.createSequentialGroup()
                        .addComponent(visor1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCalcularAjuste, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlCentro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        pnlVistaLayout.setVerticalGroup(
            pnlVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlVistaLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(pnlVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcularAjuste, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(visor1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCentro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlVista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlVista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtValxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValxActionPerformed

    private void txtValxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValxKeyTyped
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "SOLO NUMEROS");
        }
    }//GEN-LAST:event_txtValxKeyTyped

    private void txtValyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValyKeyTyped
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "SOLO NUMEROS");
        }
    }//GEN-LAST:event_txtValyKeyTyped

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if (txtValx.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "LLENE EL CAMPO A Y B PARA AGREGAR");
            txtValx.requestFocus();
        } else if (txtValy.getText().equals("")) {
             JOptionPane.showMessageDialog(this, "LLENE EL CAMPO A Y B PARA AGREGAR");
             txtValy.requestFocus();
        } else {
            fila++;

            vector[0] = (txtValx.getText());
            vector[1] = (txtValy.getText());

            DefaultTableModel dfModel = (DefaultTableModel) (tabla.getModel());
            dfModel.addRow(vector);
            tabla.setModel(dfModel);

            txtValx.setText("");
            txtValy.setText("");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (fila >= 0) {

            DefaultTableModel dfModel = (DefaultTableModel) (tabla.getModel());
            dfModel.removeRow(fila);
            tabla.setModel(dfModel);

            fila--;
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCalcularAjusteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularAjusteActionPerformed
        double x[] = new double[fila];
        double y[] = new double[fila];
        
        for(int i=0;i<fila;i++){
            x[i]=Double.valueOf(String.valueOf(tabla.getValueAt(i, 0)));
            y[i]=Double.valueOf(String.valueOf(tabla.getValueAt(i, 1)));
        }
        
        objAjuste= new AjusteCurvas();
        valores=objAjuste.calcularAjusteCurva(x, y);
        tipoFuncion=objAjuste.getTipoFuncion();
        
        for(int i=0;i<valores.length;i++){
            tablaValores.setValueAt(valores[i], i, 0);
        }
        lblTipoFuncion.setText(tipoFuncion);
        lblDesvi.setText(String.valueOf(objAjuste.getDesviacion()));
        this.frame2.setVisible(true);
       
    }//GEN-LAST:event_btnCalcularAjusteActionPerformed

    private void rSButtonRound1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound1ActionPerformed
      this.frame2.setVisible(false);
    }//GEN-LAST:event_rSButtonRound1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonMetro btnAdd;
    private rojerusan.RSMaterialButtonCircle btnCalcularAjuste;
    private rojerusan.RSButtonMetro btnDelete;
    private javax.swing.JFrame frame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDesvi;
    private javax.swing.JLabel lblTipoFuncion;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlMejorAjuste;
    private javax.swing.JPanel pnlOpcMetodo1;
    private javax.swing.JPanel pnlVista;
    private rojerusan.RSButtonIconI rSButtonIconI10;
    private rojerusan.RSButtonIconI rSButtonIconI5;
    private rojerusan.RSButtonIconI rSButtonIconI7;
    private rojerusan.RSButtonIconI rSButtonIconI8;
    private rojerusan.RSButtonIconI rSButtonIconI9;
    private rojerusan.RSButtonRound rSButtonRound1;
    private rojerusan.RSTableMetro tabla;
    private rojerusan.RSTableMetro tablaValores;
    private javax.swing.JTextField txtValx;
    private javax.swing.JTextField txtValy;
    private Visor.Visor visor1;
    // End of variables declaration//GEN-END:variables
}
