/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import javax.swing.JPanel;
import rojerusan.RSButtonIconI;

/**
 *
 * @author cesit
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    private int x, y;
    JPanel jpCentral;
    RSButtonIconI btnAux;

    public Principal() {
        initComponents();
        Teclado teclado = new Teclado();
        this.setLocationRelativeTo(null);
        this.personalizacion();
    }

    private void personalizacion() {
        this.x = this.pnlCentro.getX();
        this.y = this.pnlCentro.getY();

        jpCentral = this.pnlCentro;
        //Teclado teclado = new Teclado();
        //this.viewPanelCentro(teclado, null);
        this.repaint();

    }

    public void viewPanelCentro(Object jp, java.awt.event.MouseEvent evt) {
        try {
            this.remove(this.getContentPane().getComponentAt(x, y));
            this.repaint();
            this.getContentPane().add((Component) jp, BorderLayout.CENTER);
            this.getComponentAt(x, y).setPreferredSize(new Dimension(100, 100));
            this.revalidate();

            if (evt != null) {
                btnAux.setSelected(false);
                btnAux = (RSButtonIconI) evt.getSource();
                btnAux.setSelected(true);

            }

            this.repaint();

        } catch (Exception e) {
            System.out.println(e.getMessage() + "exception");

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnlCentro = new javax.swing.JPanel();
        pnlSuperior = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnRaices = new rojerusan.RSButtonIconI();
        btnCurvas = new rojerusan.RSButtonIconI();
        btnIntegracion = new rojerusan.RSButtonIconI();
        btnDerivacion = new rojerusan.RSButtonIconI();
        BtnTaylor = new rojerusan.RSButtonIconI();

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("CALCULADORA DE METODOS NUMERICOS ");
        jLabel1.setFocusable(false);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        pnlCentro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout pnlCentroLayout = new javax.swing.GroupLayout(pnlCentro);
        pnlCentro.setLayout(pnlCentroLayout);
        pnlCentroLayout.setHorizontalGroup(
            pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 883, Short.MAX_VALUE)
        );
        pnlCentroLayout.setVerticalGroup(
            pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 4, 4));

        btnRaices.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/transparente.png"))); // NOI18N
        btnRaices.setText("RAICES");
        btnRaices.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRaices.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRaices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRaicesMouseClicked(evt);
            }
        });
        btnRaices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaicesActionPerformed(evt);
            }
        });
        jPanel1.add(btnRaices);

        btnCurvas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/transparente.png"))); // NOI18N
        btnCurvas.setText("AJUSTE DE CURVAS");
        btnCurvas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCurvas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCurvas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCurvasMouseClicked(evt);
            }
        });
        jPanel1.add(btnCurvas);

        btnIntegracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/transparente.png"))); // NOI18N
        btnIntegracion.setText("INTEGRACIÓN");
        btnIntegracion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnIntegracion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIntegracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIntegracionMouseClicked(evt);
            }
        });
        jPanel1.add(btnIntegracion);

        btnDerivacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/transparente.png"))); // NOI18N
        btnDerivacion.setText("DERIVACIÓN");
        btnDerivacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDerivacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDerivacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDerivacionMouseClicked(evt);
            }
        });
        btnDerivacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDerivacionActionPerformed(evt);
            }
        });
        jPanel1.add(btnDerivacion);

        BtnTaylor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/transparente.png"))); // NOI18N
        BtnTaylor.setText("TAYLOR");
        BtnTaylor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnTaylor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(BtnTaylor);

        javax.swing.GroupLayout pnlSuperiorLayout = new javax.swing.GroupLayout(pnlSuperior);
        pnlSuperior.setLayout(pnlSuperiorLayout);
        pnlSuperiorLayout.setHorizontalGroup(
            pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 917, Short.MAX_VALUE)
            .addGroup(pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlSuperiorLayout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 906, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnlSuperiorLayout.setVerticalGroup(
            pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 202, Short.MAX_VALUE)
            .addGroup(pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlSuperiorLayout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );

        getContentPane().add(pnlSuperior);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRaicesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRaicesMouseClicked
        
        
        PRaices jpRaices = new PRaices();
        this.viewPanelCentro(jpRaices, evt);
        this.repaint();
    }//GEN-LAST:event_btnRaicesMouseClicked

    private void btnCurvasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCurvasMouseClicked
        PAjusteC jpAjusteC = new PAjusteC();
        this.viewPanelCentro(jpAjusteC, evt);
        this.repaint();
    }//GEN-LAST:event_btnCurvasMouseClicked

    private void btnIntegracionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIntegracionMouseClicked
        PIntegracion jpIntegracion = new PIntegracion();
        this.viewPanelCentro(jpIntegracion, evt);
        this.repaint();
    }//GEN-LAST:event_btnIntegracionMouseClicked

    private void btnDerivacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDerivacionMouseClicked
        PDerivacion jpDerivacion = new PDerivacion();
        this.viewPanelCentro(jpDerivacion, evt);
        this.repaint();
    }//GEN-LAST:event_btnDerivacionMouseClicked

    private void btnDerivacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerivacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDerivacionActionPerformed

    private void btnRaicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaicesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRaicesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonIconI BtnTaylor;
    private rojerusan.RSButtonIconI btnCurvas;
    private rojerusan.RSButtonIconI btnDerivacion;
    private rojerusan.RSButtonIconI btnIntegracion;
    private rojerusan.RSButtonIconI btnRaices;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlSuperior;
    // End of variables declaration//GEN-END:variables
}
